


<!DOCTYPE html>
<html id="htmlId">
<head>
  <title>Coverage Report > CoffeeMakerTest</title>
  <style type="text/css">
    @import "../../css/coverage.css";
    @import "../../css/idea.min.css";
  </style>
  <script type="text/javascript" src="../../js/highlight.min.js"></script>
  <script type="text/javascript" src="../../js/highlightjs-line-numbers.min.js"></script>
</head>

<body>
<div class="content">
<div class="breadCrumbs">
Current scope:     <a href="../../index.html">all classes</a>
    <span class="separator">|</span>
    <a href="../index.html">edu.ncsu.csc326.coffeemaker</a>
</div>

<h1>Coverage Summary for Class: CoffeeMakerTest (edu.ncsu.csc326.coffeemaker)</h1>

<table class="coverageStats">
<tr>
  <th class="name">Class</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
</tr>
<tr>
  <td class="name">CoffeeMakerTest</td>
<td class="coverageStat">
  <span class="percent">
    100%
  </span>
  <span class="absValue">
    (1/1)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    100%
  </span>
  <span class="absValue">
    (13/13)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    84,4%
  </span>
  <span class="absValue">
    (76/90)
  </span>
</td>
</tr>

</table>

<br/>
<br/>


<pre>
<code class="sourceCode" id="sourceCode">&nbsp;package edu.ncsu.csc326.coffeemaker;
&nbsp;import static org.junit.Assert.assertArrayEquals;
&nbsp;import static org.junit.Assert.assertEquals;
&nbsp;import static org.junit.Assert.assertThrows;
&nbsp;import static org.junit.Assert.fail;
&nbsp;import org.junit.Before;
&nbsp;import org.junit.Test;
&nbsp;import edu.ncsu.csc326.coffeemaker.exceptions.InventoryException;
&nbsp;import edu.ncsu.csc326.coffeemaker.exceptions.RecipeException;
&nbsp;
&nbsp;
<b class="fc">&nbsp;public class CoffeeMakerTest {</b>
&nbsp;	 CoffeeMaker coffeeMaker;
&nbsp;	 Recipe recipe;
&nbsp;	 Inventory inventory;
&nbsp;	 RecipeBook recipeBook;
&nbsp;	 
&nbsp;	 @Before
&nbsp;	 public void setUp() throws Exception 
&nbsp;	 {
<b class="fc">&nbsp;		 coffeeMaker = new CoffeeMaker();</b>
<b class="fc">&nbsp;		 recipe = new Recipe();</b>
<b class="fc">&nbsp;		 inventory = new Inventory();</b>
<b class="fc">&nbsp;		 recipeBook = new RecipeBook();</b>
<b class="fc">&nbsp;		 recipe.setName(&quot;R1&quot;);</b>
<b class="fc">&nbsp;		 recipe.setPrice(&quot;12&quot;);</b>
<b class="fc">&nbsp;	     recipe.setAmtChocolate(&quot;5&quot;);</b>
<b class="fc">&nbsp;		 recipe.setAmtCoffee(&quot;10&quot;);</b>
<b class="fc">&nbsp;		 recipe.setAmtMilk(&quot;6&quot;);</b>
<b class="fc">&nbsp;		 recipe.setAmtSugar(&quot;2&quot;);</b>
&nbsp;		 
&nbsp;	 }
&nbsp;	 
&nbsp;	 // This test fails because the add recipe method does not check if the recipe is null
&nbsp;	// If the recipe is null, it should not be added to the array of recipes
&nbsp;	 /*@Test
&nbsp;	 public void testAddrecipe()
&nbsp;	 {
&nbsp;		 Recipe recipe1= null;
&nbsp;		 boolean added = coffeeMaker.addRecipe(recipe1);
&nbsp;		 boolean expected = false;
&nbsp;		 assertEquals(expected, added);
&nbsp;	 }
&nbsp;	 
&nbsp;	 // It passes because the deletRecipe in the recipeBook class checks if any recipe exist in that index
&nbsp;	 @Test
&nbsp;	 public void testDeleteRecipe1()
&nbsp;	 {
&nbsp;		 String deleted= coffeeMaker.deleteRecipe(0);
&nbsp;		 String expected = null;
&nbsp;		 assertEquals(expected,deleted);
&nbsp;	 }
&nbsp;	 
&nbsp;	 // The test passes
&nbsp;	 @Test
&nbsp;	 public void testDeleteRecipe2()
&nbsp;	 {   coffeeMaker.addRecipe(recipe);
&nbsp;		 String deleted= coffeeMaker.deleteRecipe(0);
&nbsp;		 String expected = &quot;R1&quot;;
&nbsp;		 assertEquals(expected,deleted);
&nbsp;	 }
&nbsp;	 
&nbsp;	 // I don&#39;t know why I get error here
&nbsp;	 // addSugar method does not work properly because of line 182 in the Inventory class
&nbsp;	 // But what is the problem with chocolate?
&nbsp;	 @Test
&nbsp;	 public void testAddInvnetory() 
&nbsp;	 {
&nbsp;		 try 
&nbsp;		 {  
&nbsp;			 coffeeMaker.addInventory(&quot;2&quot;, &quot;12&quot;, &quot;3&quot;, &quot;6&quot;);
&nbsp;		 }
&nbsp;		 catch(InventoryException e) 
&nbsp;		 {
&nbsp;			// fail(&quot;InventoryException should not be thrown&quot;);
&nbsp;		 }
&nbsp;		 
&nbsp;		 String inventoryCheck = coffeeMaker.checkInventory();
&nbsp;		 String expected = &quot;Coffee: 17\nMilk: 27\nSugar: 18\nChocolate: 21\n&quot;;
&nbsp;		 assertEquals(expected,inventoryCheck);
&nbsp;		 
&nbsp;	 }
&nbsp;	 */
&nbsp;	 // Test if we get the subtraction of paid money and the price of the recipe
&nbsp;	 // Here the recipe can be made because all the ingredients are enough
&nbsp;	@Test
&nbsp;	public void testMakeCoffee1()
&nbsp;	
<b class="fc">&nbsp;	{   coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;		int paidAmount = 24;</b>
&nbsp;		try {
<b class="fc">&nbsp;			coffeeMaker.addInventory(&quot;15&quot;, &quot;15&quot;, &quot;15&quot;, &quot;15&quot;);</b>
<b class="fc">&nbsp;		} catch (InventoryException e) {</b>
<b class="fc">&nbsp;			e.getMessage();</b>
<b class="nc">&nbsp;		}</b>
<b class="fc">&nbsp;		int expected = 24-12;</b>
<b class="fc">&nbsp;		int result = coffeeMaker.makeCoffee(0, paidAmount);</b>
<b class="fc">&nbsp;		assertEquals(expected, result);</b>
&nbsp;	}
&nbsp;	 
&nbsp;	// Here the expected return value is 6 since the paid money is not enough and the transaction does not take place
&nbsp;	@Test
&nbsp;	public void testMakeCoffee2()
&nbsp;	
<b class="fc">&nbsp;	{   coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;		int paidAmount = 6;</b>
&nbsp;		try {
<b class="fc">&nbsp;			coffeeMaker.addInventory(&quot;15&quot;, &quot;15&quot;, &quot;15&quot;, &quot;15&quot;);</b>
<b class="fc">&nbsp;		} catch (InventoryException e) {</b>
<b class="fc">&nbsp;			e.getMessage();</b>
<b class="nc">&nbsp;		}</b>
<b class="fc">&nbsp;		int expected = 6;</b>
<b class="fc">&nbsp;		int result = coffeeMaker.makeCoffee(0, paidAmount);</b>
<b class="fc">&nbsp;		assertEquals(expected, result);</b>
&nbsp;	}
&nbsp;	
&nbsp;	// Here the ingredients are not enough so the recipe can not be made
&nbsp;	@Test
&nbsp;    public void testMakeCoffee3()
<b class="fc">&nbsp;	{   coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;		int paidAmount = 6;</b>
&nbsp;		try {
<b class="fc">&nbsp;			coffeeMaker.addInventory(&quot;2&quot;, &quot;15&quot;, &quot;4&quot;, &quot;1&quot;);</b>
<b class="fc">&nbsp;		} catch (InventoryException e) {</b>
<b class="fc">&nbsp;			e.getMessage();</b>
<b class="nc">&nbsp;		}</b>
<b class="fc">&nbsp;		int expected = 6;</b>
<b class="fc">&nbsp;		int result = coffeeMaker.makeCoffee(0, paidAmount);</b>
<b class="fc">&nbsp;		assertEquals(expected, result);</b>
&nbsp;	}
&nbsp;
&nbsp;	@Test
&nbsp;	public void testMakeCoffee5()
&nbsp;	{
&nbsp;
<b class="fc">&nbsp;		int paidAmount = 6;</b>
&nbsp;		try {
<b class="fc">&nbsp;			coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;			coffeeMaker.getRecipes()[0] = null;</b>
<b class="fc">&nbsp;			coffeeMaker.addInventory(&quot;2&quot;, &quot;15&quot;, &quot;4&quot;, &quot;1&quot;);</b>
<b class="fc">&nbsp;		} catch (InventoryException e) {</b>
<b class="fc">&nbsp;			e.getMessage();</b>
<b class="nc">&nbsp;		}</b>
<b class="fc">&nbsp;		int expected = 6;</b>
<b class="fc">&nbsp;		int result = coffeeMaker.makeCoffee(0, paidAmount);</b>
<b class="fc">&nbsp;		assertEquals(expected, result);</b>
&nbsp;	}
&nbsp;
&nbsp;	@Test
&nbsp;	public void testMakeCoffee6()
&nbsp;	{
&nbsp;
<b class="fc">&nbsp;		int paidAmount = 6;</b>
&nbsp;		try {
<b class="fc">&nbsp;			inventory.setCoffee(0);</b>
<b class="fc">&nbsp;			inventory.setChocolate(0);</b>
<b class="fc">&nbsp;			inventory.setMilk(0);</b>
<b class="fc">&nbsp;			inventory.setSugar(0);</b>
<b class="fc">&nbsp;			recipe.setAmtMilk(&quot;10&quot;);</b>
<b class="fc">&nbsp;			recipe.setPrice(&quot;2&quot;);</b>
<b class="fc">&nbsp;			coffeeMaker.addRecipe(recipe);</b>
&nbsp;		}
<b class="nc">&nbsp;		catch (RecipeException e) {</b>
<b class="nc">&nbsp;			e.getMessage();</b>
<b class="fc">&nbsp;		}</b>
<b class="fc">&nbsp;		int expected = 6;</b>
<b class="fc">&nbsp;		int result = coffeeMaker.makeCoffee(0, paidAmount);</b>
<b class="fc">&nbsp;		assertEquals(expected, result);</b>
&nbsp;	}
&nbsp;
&nbsp;	@Test
&nbsp;	public void testMakeCoffee4() {
<b class="fc">&nbsp;		Throwable exception = assertThrows(</b>
&nbsp;				NullPointerException.class, () -&gt; {
<b class="fc">&nbsp;					int paidAmount = 6;</b>
&nbsp;					try {
<b class="fc">&nbsp;						recipe = null;</b>
<b class="fc">&nbsp;						coffeeMaker.addRecipe(recipe);</b>
<b class="nc">&nbsp;						coffeeMaker.addInventory(&quot;2&quot;, &quot;15&quot;, &quot;4&quot;, &quot;1&quot;);</b>
<b class="nc">&nbsp;					} catch (InventoryException e) {</b>
<b class="nc">&nbsp;						e.getMessage();</b>
<b class="nc">&nbsp;					}</b>
&nbsp;
<b class="nc">&nbsp;					coffeeMaker.makeCoffee(10, paidAmount);</b>
&nbsp;				}
&nbsp;		);
<b class="fc">&nbsp;		assertEquals(&quot;Cannot invoke \&quot;edu.ncsu.csc326.coffeemaker.Recipe.equals(Object)\&quot; because \&quot;r\&quot; is null&quot;, exception.getMessage());</b>
&nbsp;	}
&nbsp;
&nbsp;	// This test fails because the method does not check for negative arguments
&nbsp;	 @Test
&nbsp;	public void testNegativeArgumentsForMakeCoffee1() {
<b class="fc">&nbsp;		Throwable exception = assertThrows(</b>
&nbsp;				IllegalArgumentException.class, () -&gt; {
<b class="fc">&nbsp;					coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;					int paidAmount = -12;</b>
&nbsp;					try {
<b class="fc">&nbsp;						coffeeMaker.addInventory(&quot;2&quot;, &quot;15&quot;, &quot;4&quot;, &quot;1&quot;);</b>
<b class="fc">&nbsp;					} catch (InventoryException e) {</b>
<b class="fc">&nbsp;						e.getMessage();</b>
<b class="nc">&nbsp;					}</b>
<b class="fc">&nbsp;					coffeeMaker.makeCoffee(0, paidAmount);</b>
&nbsp;				    }
&nbsp;				);
<b class="nc">&nbsp;		assertEquals(&quot;The passed argument as the paid price should be positive integer&quot;, exception.getMessage());</b>
&nbsp;    }
&nbsp;	 
&nbsp;    // This test passes
&nbsp;	 @Test
&nbsp;	 public void testNegativeArgumentsForMakeCoffee2() {
<b class="fc">&nbsp;			Throwable exception = assertThrows(</b>
&nbsp;					IndexOutOfBoundsException.class, () -&gt; {
<b class="fc">&nbsp;						coffeeMaker.addRecipe(recipe);</b>
<b class="fc">&nbsp;						int paidAmount = 12;</b>
&nbsp;						try {
<b class="fc">&nbsp;							coffeeMaker.addInventory(&quot;2&quot;, &quot;15&quot;, &quot;4&quot;, &quot;1&quot;);</b>
<b class="fc">&nbsp;						} catch (InventoryException e) {</b>
<b class="fc">&nbsp;							e.getMessage();</b>
<b class="nc">&nbsp;						}</b>
<b class="fc">&nbsp;						coffeeMaker.makeCoffee(-4, paidAmount);</b>
&nbsp;					    }
&nbsp;					);
<b class="fc">&nbsp;			assertEquals(&quot;Index -4 out of bounds for length 4&quot;, exception.getMessage());</b>
&nbsp;	    }
&nbsp;
&nbsp;	 
&nbsp;	 
&nbsp;
&nbsp;}
</code>
</pre>
</div>

<script type="text/javascript">
(function() {
    var msie = false, msie9 = false;
    /*@cc_on
      msie = true;
      @if (@_jscript_version >= 9)
        msie9 = true;
      @end
    @*/

    if (!msie || msie && msie9) {
      hljs.highlightAll()
      hljs.initLineNumbersOnLoad();
    }
})();
</script>

<div class="footer">
    
    <div style="float:right;">generated on 2023-02-24 13:55</div>
</div>
</body>
</html>
